### ISSUE TITLE
Adding ScalaJs Compatibility to CIRCE

### ISSUE THREAD

**Issue by omidb** [travisbrown/circe#12]
Thanks Travis for the library,

Is it compatible with ScalaJS?

**Comment by travisbrown** [comment]
No, not currently. Given that Shapeless supports it and it's [coming soon to cats](https://github.com/non/cats/pull/427), it shouldn't be too difficult here. You'd also need a parser (I'm assuming there are probably easier ways than adding Scala.js support to Jawn, since it's JavaScript, after all).

There are a number of things that are higher priorities for me, but I'd be happy to accept a pull request once cats is published with Scala.js support.

**Comment by travisbrown** [comment]
@omidb Also, if you'd like to rephrase the issue as a request for Scala.js support, I'd be happy to slap a milestone label on it (probably 0.2, since I'd like to publish an 0.1 sooner rather than later, and I'm not sure what the timing will look like for cats).

**Comment by ngbinh** [comment]
:+1: for Scala.js support. Just FYI: here's upickle's parser: https://github.com/lihaoyi/upickle-pprint/blob/master/upickle/js/src/main/scala/upickle/json/package.scala

**Comment by InTheNow** [comment]
Cats support is done, just waiting for a second :+1: from a maintainer :wink:  - https://github.com/non/cats/pull/427

**Comment by ngbinh** [comment]
https://github.com/non/cats/pull/427 has been merged

**Comment by travisbrown** [comment]
How would people feel about some kind of "best effort" Scala.js support? I'm imagining something like the following:

1. We don't include Scala.js in the Travis CI config (at least for now).
2. Anyone submitting a substantial PR would be expected to run the Scala.js build locally.
3. We make sure Scala.js support is working before releases.

In part because this is such a young project, I don't really want to slow down PRs and deal with a lot of CI fussiness just to be 100% sure that Scala.js support is never broken in master.

**Comment by ngbinh** [comment]
I understand the pain. But doing so would make scala.js support 2nd class citizen. Also, does that mean we cannot have *official* scala.js artifacts on Maven? 

Can you please point out the pain you experience with supporting scala.js?

**Comment by InTheNow** [comment]
@travisbrown All the cats CI issues have been resolved so it would make sense to me to get scalajs support in asap (assuming of course, that's your end goal). Shout if you need any help, btw

**Comment by alexarchambault** [comment]
@travisbrown A way of achieving that could be to have two branches, differing only by their `.travis.yml`.

`master` would compile for JVM Scala, and a `scalajs` branch would compile for for Scala.js. `master` would be merged in `scalajs` from time to time, and possible Scala.js proper issues fixed then.
