### ISSUE TITLE
DecodingFailure contains no useful information

### ISSUE THREAD

**Issue by Centaur** [travisbrown/circe#288]
When a `DecodingFailure` happens, I expect it to contain some information helpful for debugging, i.e., which part of the json string cannot be decoded. But its `message` is just some type name such as `String`, `Long`, etc and its `history` is always an empty `List`. Or how can I get more information from a `DecodingFailure` ?

**Comment by olafurpg** [comment]
There's a `Show[DecodingFailure]` instance in [Error.scala](https://github.com/travisbrown/circe/blob/7d799b9aee6f96a693dabd17eb514c9a719645c2/core/shared/src/main/scala/io/circe/Error.scala#L92-L99) that shows JS style selections. To use it, 

```scala
import io.circe._, io.circe.generic.auto._, io.circe.parser._
import cats.syntax.show._
case class Foo(col: Option[Int])
val result = parse("""{ "col": "bar" }""").flatMap(_.as[Foo]).leftMap(_.show)
result: cats.data.Xor[String, Foo] = Left("DecodingFailure at .col: Int")
```

**Comment by Centaur** [comment]
@olafurpg Thank you very much. That is very helpful.

**Comment by olafurpg** [comment]
@imarios not that I'm aware of. For that to work you probably need positions attached to json nodes.

**Comment by imarios** [comment]
@olafurpg thank you!

**Comment by joan38** [comment]
Why are we not getting any stack trace when this happens? At least to know where in the code this is happening would be great.

**Comment by psttf** [comment]
@joan38 Circe seems to suppress exception stack traces for performance reasons. See #233. Looks like one has to wrap Circe exception to get more info for tracing it.

**Comment by travisbrown** [comment]
@psttf It's true that part of the reason that Circe suppresses stack traces is performance, but that's largely incidental. The primary reason is that Circe never throws exceptions, and idiomatic Circe usage relies on ordinary return values to represent decoding failures. (Note that it's of course possible to end up with e.g. stack overflows or initialization order null-pointer exceptions in code that uses Circe, but these are actually exceptional cases, not _failures_ in the sense that libraries like Circe use the word.)

The idea is that a `DecodingFailure` is essentially just an ordinary case class containing two pieces of data: a message (usually indicating the target type) and a path to the error position (where by path we mean a series of JSON navigation operations, although it's likely we'll also include character positions in a future version of Circe, assuming the parser supports it).

As a kind of compromise with convenience, we make `DecodingFailure` extend `Exception`, so that it can be used as the failure side of a `Try` or `Either[Throwable, *]` without being wrapped, but it's not _really_ an exception, and it's not intended to be thrown.

Since `DecodingFailure` is not intended to be thrown, we decided that we might as well suppress the stack trace, which is a relatively expensive operation. In general the performance cost of creating the stack trace for each decoding failure wouldn't make much of a difference, but there are idiomatic patterns where it might (like error accumulation for a JSON list where we might need to construct a large number of failure instances for a single input), so we just don't do it.

**Comment by psttf** [comment]
@travisbrown Thank you for the explanation! It turns out that I was confused by the fact that `DecodingFailure` extends `Exception`. This makes it possible to apply `IO.fromEither` and the like to it, but it results in having untraceable errors without stack traces in error logs. Maybe it is better to not extend `Exception` at all? Then it will always be necessary to wrap `DecodingFailure` in an `Exception` before applying `IO.fromEither` and automatically get traceable errors? And for convenience there may be a syntax method to do such wrapping easily in a `Decoder.Result`.

**Comment by travisbrown** [comment]
@psttf This is something we've thought a lot about, and while I definitely agree that the current approach isn't perfect, the trade-offs are something we've considered. Not saying it could never change, but I think it's unlikely.

In general my recommendation would be to try to use alternative approaches to error handling that don't require you to deal with undifferentiated exceptions in `IO` at some high level, which is when stack traces would be valuable.

I know that's not always practical, though, and if you _do_ decide to wrap the failure in order to get a stack trace, one additional benefit of the fact that `DecodingFailure` extends `Exception` is that  you can use the Java `Throwable` hierarchy's `Throwable cause` constructor, instead of having to use a custom `Exception` class or make decisions about how to represent the `DecodingFailure` as a message string.
