### ISSUE TITLE
Useless compile error while lacking encoder/decoder

### ISSUE THREAD

**Issue by jilen** [travisbrown/circe#35]
If there is no encode for date, then compiler complains
```
 [error] /home/jilen/workspace/jfc-test/src/main/scala/Foo.scala:26: diverging implicit expansion for type io.circe.Encoder.Secondary[this.Out]
[error] starting with method encodeCaseClass in trait GenericInstances
```

> Is there any chance to improve the error reporting ?

```scala
import io.circe._
import io.circe.generic.auto._
import io.circe.syntax._

import java.util.Date
case class Foo(
  date: Date,
  number: Int,
  str: String)

object App {

  def encodesDate(fmt: String): Encoder[Date] = new Encoder[Date] {
    def apply(a: Date) = {
      val sdf = new java.text.SimpleDateFormat(fmt)
      Json.string(sdf.format(a))
    }
  }



  def main(args: Array[String])  {
    //implicit val DateEncodes = encodesDate("yyyy-MM-dd HH:mm:ss")
    val f = Foo(new Date, 1, "fff")
    println(f.asJson.noSpaces)
  }
}
```

**Comment by travisbrown** [comment]
Yeah, that's a pretty terrible error message—thanks for pointing it out.

The implementation of the generic derivation mechanism will be changing with #30, which I'm hoping to get done tomorrow, so after that dust settles I'll revisit this and #34, since things might be a little different by then. We should be able to use `@implicitNotFound` in a few places to improve these messages a lot (see for example [this message](https://github.com/finagle/finch/blob/3089cf1ca65eeabfc10458e01d571a23fae195e8/core/src/main/scala/io/finch/route/ToService.scala#L16) in Finch).

**Comment by djx314** [comment]
+1 to use implicitNotFound !
To decode and encode date, juest implicit
```scala
  implicit val dateTimeEncoder: Encoder[DateTime] = Encoder.instance(a => a.getMillis.asJson)
  implicit val dateTimeDecoder: Decoder[DateTime] = Decoder.instance(a => a.as[Long].map(new DateTime(_)))
```
Because of date has many format, I suggest that defined it in the documention and don't add a default format in the jfc.

**Comment by travisbrown** [comment]
I'm going to go ahead and close this since the following is a huge improvement:

```scala
<console>:59: error: could not find implicit value for parameter e: io.circe.Encoder[Foo]
           println(f.asJson.noSpaces)
                     ^
```

I'm not actually sure there's much additional useful information we could add with `@implicitNotFound` in this case, apart from maybe a pointer to the docs.
