### ISSUE TITLE
Auto generated `Decoder` is `null`

### ISSUE THREAD

**Issue by TimSoethout** [travisbrown/circe#380]
I ran into a situation where my `Decoder` turned out to be `null`. I reproduced it in the REPL with a smaller example:

```scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

import io.circe.Decoder
import io.circe.generic.auto._

sealed trait Command
object Command {
  implicit val commandDecoder: Decoder[Command] = Decoder[Command]
}

final case class Create(id: Int) extends Command

val decoder: Decoder[Command] = Decoder[Command]

Command.commandDecoder

// Exiting paste mode, now interpreting.

import io.circe.Decoder
import io.circe.generic.auto._
defined trait Command
defined object Command
defined class Create
decoder: io.circe.Decoder[Command] = null
res0: io.circe.Decoder[Command] = null
```

It seems to be related to defining the decoder in the Companion object.

**Comment by travisbrown** [comment]
The issue here is that you're defining an implicit value using `Decoder.apply`, which will go out and look for… an implicit value of the same type. The compiler will assume your definition is recursive, and since this is a `val` that hasn't been initialized yet, you end up with `null`.

The supported way of handling this situation is to use `io.circe.generic.semiauto.deriveDecoder`, but you could also use Shapeless's `cachedImplicit` or (I think) just drop the type annotation. I'd go with `deriveDecoder`, though.

**Comment by TimSoethout** [comment]
Doh. You're right. It has nothing to do with circe at all:

```scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

object Command {
  def getCommand(implicit command: Command): Command = command

  implicit val command: Command = getCommand
}

Command.command

// Exiting paste mode, now interpreting.

defined object Command
res1: Command = null
```

Thanks for the clear and quick response!
