### ISSUE TITLE
Can decode[ClassName](json: String` be used for incomplete json?

### ISSUE THREAD

**Issue by yoppworks-luke** [travisbrown/circe#426]
Consider the following code:

```
val json = """ {"firstName": "John"}"""
case class Person(firstName: String, lastName: String)
decode[Person](json)
```

Currently this returns a `Left(Some kind of cursor error)` because "lastName" is missing in the json string. I'm having to use an actual cursor with `getOrElse` and traverse the json and build out the case class. Anyway `decode` can supply default values like empty string, false, etc for that particular field?

**Comment by darienmt** [comment]
In some cases could be better to use Option[T] instead of default value:
```
scala> import io.circe._, io.circe.generic.auto._, io.circe.parser._, io.circe.syntax._
import io.circe._
import io.circe.generic.auto._
import io.circe.parser._
import io.circe.syntax._

scala> case class Person(firstName: String, lastName: Option[String])
defined class Person

scala> val json = """ {"firstName": "John"}"""
json: String = " {"firstName": "John"}"

scala> decode[Person](json)
res0: cats.data.Xor[io.circe.Error,Person] = Right(Person(John,None))
```

**Comment by travisbrown** [comment]
In addition to @darienmt's answer (which is the simplest and usually best way to handle this kind of situation), circe also provides generic derivation for partial case classes:

```scala
import io.circe.generic.auto._, io.circe.jawn.decode
import shapeless.Witness, shapeless.labelled.{ field, FieldType }

case class Person(firstName: String, lastName: String)

val json = """ {"firstName": "John"}"""

val Right(partial) = decode[FieldType[Witness.`'lastName`.T, String] => Person](json)
```
And then:
```scala
scala> partial(field("McBar"))
res0: Person = Person(John,McBar)
```

This would be substantially cleaner if you had distinct types—the `Witness` and `field` business is only necessary because you have to disambiguate between the two `String` fields.

You could also decode the JSON as a patch for your case class:

```scala
scala> import io.circe.generic.auto._, io.circe.jawn.decode
import io.circe.generic.auto._
import io.circe.jawn.decode

scala> case class Person(firstName: String, lastName: String)
defined class Person

scala> val json = """ {"firstName": "John"}"""
json: String = " {"firstName": "John"}"

scala> val Right(patch) = decode[Person => Person](json)
patch: Person => Person = ...

scala> patch(Person("Foo", "McBar"))
res0: Person = Person(John,McBar)
```

Either the partial or patching decoder approaches arguably allow you to keep serialization concerns out of your data model a little more cleanly. You can read more about the motivation and implementation in my blog post [here](http://meta.plasm.us/posts/2015/06/21/deriving-incomplete-type-class-instances/).
